import type { ITheme } from "@xterm/xterm";

export interface TerminalTheme {
  id: string;
  label: string;
  /** triplete RGB del fondo, para el CSS var que pinta el área del terminal */
  bgRgb: string;
  colors: ITheme;
}

export const TERMINAL_THEMES: TerminalTheme[] = [
  {
    id: "ratatoskr",
    label: "Ratatoskr",
    bgRgb: "12 12 13",
    colors: {
      background: "#0c0c0d",
      foreground: "#e8e8e8",
      cursor: "#e8e8e8",
      cursorAccent: "#0c0c0d",
      selectionBackground: "#ffffff2b",
      black: "#2a2a2c",
      red: "#ff6b6b",
      green: "#66d18c",
      yellow: "#e5c07b",
      blue: "#6ba6ff",
      magenta: "#c792ea",
      cyan: "#56c8d8",
      white: "#d6d6d6",
      brightBlack: "#5c5c5e",
      brightRed: "#ff8f8f",
      brightGreen: "#8ce4ae",
      brightYellow: "#f0d399",
      brightBlue: "#8fbfff",
      brightMagenta: "#dcb3f2",
      brightCyan: "#7fdbe8",
      brightWhite: "#f5f5f5",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    bgRgb: "30 30 46",
    colors: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      cursorAccent: "#1e1e2e",
      selectionBackground: "#585b7066",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#cba6f7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#cba6f7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    bgRgb: "26 27 38",
    colors: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#1a1b26",
      selectionBackground: "#41486866",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
  {
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    bgRgb: "40 40 40",
    colors: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      cursorAccent: "#282828",
      selectionBackground: "#66592466",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    id: "nord",
    label: "Nord",
    bgRgb: "46 52 64",
    colors: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      cursorAccent: "#2e3440",
      selectionBackground: "#4c566a66",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
];

export function getTheme(id: string): TerminalTheme {
  return TERMINAL_THEMES.find((t) => t.id === id) ?? TERMINAL_THEMES[0];
}
